name: setonix_server
description: The Linwood Setonix game server
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  args: ^2.4.2
  bloc: ^9.0.0
  logging: ^1.2.0
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: 0bdc62d3af7f31e19a694d9cd39fe020dced8754
      path: packages/networker/networker
  networker_socket:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: fa036587c2a26db6455dd063701aef32b3531800
      path: packages/networker/networker_socket
  consoler:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      ref: 4ac7cb36efb16b129b36d4ae87eacfaec8a1ee4b
      path: packages/consoler
  path: ^1.9.0
  setonix_api:
    path: ../api
  bloc_concurrency: ^0.3.0
  dart_mappable: ^4.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  dart_mappable_builder: ^4.2.3
  build_runner: ^2.4.12
